on:
  push:
    branches: [ master ]

jobs:
  publish:
    strategy:
      matrix:
        npmrc:
          - "registry=https://npm.pkg.github.com/${{ github.repository_owner }}"
          - "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com"
        include:
          - name: "@${{ github.repository }}"
          - repository_url: "${{ github.server_url }}/${{ github.repository }}"
      fail-fast: false

    env:
      version: "1.0.0-g${{ github.sha }}-${{ github.job }}"

    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Add local .npmrc file
        run: echo "${{ matrix.npmrc }}" > .npmrc

      - name: Create package
        run: |
          cat <<- EOF > package.json
          {
            "name": "${{ matrix.name }}",
            "version": "${{ env.version }}",
            "repository": "${{ matrix.repository_url }}"
          }
          EOF

      - name: Publish package
        run: npm publish

      - name: Remove package
        run: rm package.json

      - name: Create empty package
        run: npm init -y

      - name: Install package
        run: npm install ${{ matrix.name }}@${{ env.version }}

      - name: Install unscoped package from npm
        run: npm install path@0.12.7

      - name: Install scoped package from npm
        run: npm install @npm/types@1.0.0
