on:
  push:
    branches: [ master ]

jobs:
  publish:
    strategy:
      matrix:
        npmrc: ["registry=https://npm.pkg.github.com/${{ github.repository_owner }}"]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Add local .npmrc file
        run: echo "${{ matrix.npmrc }}" > .npmrc

      - name: Create package
        run: |
          cat <<- EOF > package.json
          {
            "name": "@${{ github.repository }}",
            "version": "1.0.0-g${{ github.sha }}",
            "repository": "${{ github.server_url }}/${{ github.repository }}"
          }
          EOF

      - name: Publish package
        run: npm publish

      - name: Remove package
        run: rm package.json

      - name: Create empty package
        run: npm init -y

      - name: Install package
        run: npm install @${{ github.repository }}@1.0.0-g${{ github.sha }}
