on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to GitHub Packages
        run: echo '//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}' > ~/.npmrc

      - name: Add local .npmrc file
        run: echo "registry=https://npm.pkg.github.com/${{ github.repository_owner }}" > .npmrc

      - name: Create package
        run: |
          cat <<- EOF > package.json
          {
            "name": "@${{ github.repository }}",
            "version": "1.0.0-g${{ github.sha }}",
            "repository": "${{ github.server_url }}/${{ github.repository }}"
          }
          EOF

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove package
        run: rm package.json

      - name: Install package
        run: npm install @${{ github.repository }}@1.0.0-g${{ github.sha }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
