on:
  push:
    branches: [ master ]

jobs:
  publish:
    strategy:
      matrix:
        registry:
          - "registry"
          - "@${{ github.repository_owner }}:registry"
        registry_url:
          - "https://npm.pkg.github.com"
          - "https://npm.pkg.github.com/${{ github.repository_owner }}"
          - "https://npm.pkg.github.com/@${{ github.repository_owner }}"
        include:
          - name: "@${{ github.repository }}"
          - repository_url: "${{ github.server_url }}/${{ github.repository }}"
      fail-fast: false

    env:
      version: "1.0.0-g${{ github.sha }}-${{ strategy.job-index }}"
      npmrc: "${{ matrix.registry }}=${{ matrix.registry_url }}"
      yarnrc: "\"${{ matrix.registry }}\" \"${{ matrix.registry_url }}\""

    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
        if: ${{ always() }}

      - name: Add local .npmrc file
        run: echo "${{ env.npmrc }}" > .npmrc
        if: ${{ always() }}

      - name: Create package
        run: |
          cat <<- EOF > package.json
          {
            "name": "${{ matrix.name }}",
            "version": "${{ env.version }}",
            "repository": "${{ matrix.repository_url }}"
          }
          EOF
        if: ${{ always() }}

      - name: Publish package
        run: npm publish
        if: ${{ always() }}

      - name: Remove package
        run: rm package.json
        if: ${{ always() }}

      - name: Create empty package
        run: npm init -y
        if: ${{ always() }}

      - name: Install package from GitHub
        run: npm install ${{ matrix.name }}@${{ env.version }}
        if: ${{ always() }}

      - name: Install unscoped package from npm
        run: npm install path@0.12.7
        if: ${{ always() }}

      - name: Install scoped package from npm
        run: npm install @npm/types@1.0.0
        if: ${{ always() }}

      - name: Clean up
        run: rm -R *
        if: ${{ always() }}

      - name: Add local .yarnrc file
        run: echo '${{ env.yarnrc }}' > .yarnrc
        if: ${{ always() }}

      - name: Add package using Yarn
        run: yarn add ${{ matrix.name }}@${{ env.version }}
        if: ${{ always() }}
